<div class="df">
	<div class="df-admin">
		<div class="df-system">
			<div class="df-config">
				<div class="df-extensions">
					<ul class="df-extensions">
						<li class="df-captions">
							<ul class="df-row">
								<li class="df-name">Услуга</li>
								<li class="df-enabled">Включена</li>
								<li class="df-expired">Оплачена до</li>
								<li class="df-price">В месяц</li>
								<li class="df-buy"></li>
							</ul>
						</li>
						<li class="df-extension">
							<ul class="df-row">
								<li class="df-name">
									<a href="javascript:void(0);">ChronoPay</a>
								</li>
								<li class="df-enabled">
									<select>
										<option selected="selected">да</option>
										<option>нет</option>
									</select>
								</li>
								<li class="df-expired">2012-02-10</li>
								<li class="df-price">$30</li>
								<li class="df-buy">
									<a href="javascript:void(0);">продлить</a>
								</li>
							</ul>
						</li>
						<li class="df-extension">
							<ul class="df-row">
								<li class="df-name">
									<a href="javascript:void(0);">Loginza</a>
								</li>
								<li class="df-enabled">
									нет
								</li>
								<li class="df-expired"></li>
								<li class="df-price">$10</li>
								<li class="df-buy">
									<a href="javascript:void(0);">купить</a>
								</li>
							</ul>
						</li>
						<li class="df-extension">
							<ul class="df-row">
								<li class="df-name">
									<a href="javascript:void(0);">Единый кошелёк</a>
								</li>
								<li class="df-enabled">
									<select>
										<option>да</option>
										<option selected="selected">нет</option>
									</select>
								</li>
								<li class="df-expired">2011-05-19</li>
								<li class="df-price">$10</li>
								<li class="df-buy">
									<a href="javascript:void(0);">продлить</a>
								</li>
							</ul>
						</li>
						<li class="df-extension">
							<ul class="df-row">
								<li class="df-name">
									<a href="javascript:void(0);">Робокасса</a>
								</li>
								<li class="df-enabled">
									<select>
										<option selected="selected">да</option>
										<option>нет</option>
									</select>
								</li>
								<li class="df-expired">никогда</li>
							</ul>
						</li>
						<li class="df-extension">
							<ul class="df-row">
								<li class="df-name">
									<a href="javascript:void(0);">Поисковая оптимизация</a>
								</li>
								<li class="df-enabled">
									<select>
										<option selected="selected">да</option>
										<option>нет</option>
									</select>
								</li>
								<li class="df-expired">2011-03-10</li>
								<li class="df-price">$30</li>
								<li class="df-buy">
									<a href="javascript:void(0);">продлить</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>