<?php /** @var Df_PromoGift_Block_Cart_Gift_Highlighter $this */ ?>

<?php
    if (!df_empty ($this->getGiftingQuoteItemIds ())) {

		$quoteItemIds = implode (", ", $this->getGiftingQuoteItemIds ());

		?>
			<script type='text/javascript'>
				window.df = {} || window.df;
				window.df.promo_gift = {} || window.df.promo_gift;
				window.df.promo_gift.giftingQuoteItems = [<?php echo $quoteItemIds; ?>];
				window.df.promo_gift.giftingQuoteItemTitle = '<?php echo $this->__ ("Ваш подарок!"); ?>';
			</script>
		<?php
	}

