<script type="text/javascript">
jQuery(function(){
	jQuery("a[rel='photo']").colorbox({
		slideshow:true,
		slideshowSpeed:<?php echo $this->getSlideShowSpeed();?>
	});
	jQuery(".slide-show").click(function(){
		jQuery("a[rel='photo']:first").click();
	});
});
</script>
<?php $currentAlbum = Mage::registry('current_album');?>
<?php $mode = $this->getRequest()->getParam('mode');?>
<?php $mode=($mode==""||$mode=="detail")?"detail":"simple";?>
<?php $backgroundColor= $this->getStoreBackgroundColor($mode)?>
<?php $defaultBackgroundColor = $this->getDefaultBackgroundColor();?>
<?php $photoThumbnailSize = $this->getPhotoThumbnailSize($currentAlbum);?>
<?php $albumThumbnailSize = $this->getAlbumThumbnailSize();?>
<?php $slideshowSize = $this->getSlideshowSize($currentAlbum);?>
<?php $collection = $this->getPhotos();?>
<?php $this->getToolbar()->setCollection($collection);?>

<div id="mw_gallery">
	<div class="head_title">
		<h2><?php echo $currentAlbum->getTitle()?></h2>
		<label><?php if($this->showAlbumUpdateDate()):?><?php echo date('M d, Y',strtotime($currentAlbum->getUpdateTime()));?><?php endif;?></label>
		<p class="teaser"><?php echo $currentAlbum->getContent() ?></p>
	</div>
	<!-- Subalbum list -->
	<div class="gallery-container album">		
		<ul>
			<?php $i=0;
				$collection1 = $this->getSubAlbums();
				foreach ($collection1 as $item) { ?>
				<?php if (++$i%5 ==0): ?>
				<li class="item last"  >
				<?php else:?>
				<li class="item" style="width:<?php echo $albumThumbnailSize['width']+'20'.'px'; ?>">
				<?php endif;?>
					<p  style="background-color:rgb(<?php echo $defaultBackgroundColor[0].",".$defaultBackgroundColor[1].",".$defaultBackgroundColor[2]?>);" class="width_img">	
						<a href="<?php echo $this->getUrl($this->getUrlRewrite($item)); if($this->_getStore()->getCode()!="default") echo '?___store='.$this->_getStore()->getCode() ?>" alt="<?php echo $item->getTitle() ?>" >
							<img class="bg_img_allbum" src="<?php echo $this->helper('gallery/image')->init($item->getFilename())->resize($albumThumbnailSize['width'], $albumThumbnailSize['height']) ?>" alt="magento gallery" />
						</a>
					</p>
					<h5><a href="<?php echo $this->getUrl($this->getUrlRewrite($item)); if($this->_getStore()->getCode()!="default") echo '?___store='.$this->_getStore()->getCode() ?>" alt="View Project"><?php echo $item->getTitle() ?></a></h5>
					<label><?php if($this->showAlbumUpdateDate()):?> <?php echo date('M d, Y',strtotime($item->getUpdateTime()));?><?php endif;?></label>
					<p class="disp_none"><?php if($this->showTotalPhotos()):?><?php echo $this->__('Total photos:') ?><?php echo $this->getPhotosOfAlbum($item)->getSize();?> <?php endif;?></p>
					<p class="desc_album"><?php echo $item->getDescription() ?></p>
				</li>
			<?php } ?>
			
			
		</ul>
		<div class="clear_both"><span> &nbsp; </span></div>
	</div>
	
	<?php echo $this->getToolbar()->toHtml();?>
	
	<!-- Photos list -->
	<?php 
	$className=($mode=="simple")?"simple_photo":"photo";
	?>
	<div class="gallery-container album <?php echo $className;?>">
		<ul>
			<?php $i=0; $collection = $this->getToolbar()->getCollection();?>
				<?php foreach ($collection as $item) { ?>
				<?php if (++$i%4 ==0): ?>
				<li class="item last"  >
				<?php else:?>
				<li class="item">
				<?php endif;?>
					<p class="width_img" style="background-color:rgb(<?php echo $backgroundColor[0].",".$backgroundColor[1].",".$backgroundColor[2]?>);">	
						<a href="<?php echo trim(Mage::getUrl('gallery/p'),'/')."#".$this->getUrlRewrite($item); if($this->_getStore()->getCode()!="default") echo '?___store='.$this->_getStore()->getCode()?>" title="<?php $item->getTitle()?>">
						<img src="<?php echo $this->helper('gallery/image')->init($item->getFilename(),$mode)->resize($photoThumbnailSize['width'], $photoThumbnailSize['height']) ?>" style="width:<?php echo $photoThumbnailSize['width'].'px'; ?>" alt="magento gallery"  /></a>
					</p>
					<?php if($this->getSlideShowPhotosAs() == Df_Gallery_Block_Gallery::$PHOTOS_OF_CURRENT_PAGE):?>
					<h5>
						<a style="display:none;" href="<?php echo $this->helper('gallery/image')->init($item->getFilename())->resize($slideshowSize['width'], $slideshowSize['height'],false) ?>" rel="photo" title="<?php echo $item->getTitle()?>"></a>
					</h5>
					<?php endif;?>
					<?php if($this->getToolbar()->getCurrentMode()=='detail'):?>
					<div class="photo_info">
						<?php if($this->showPhotoTitle($currentAlbum)):?>
							<h5><a href="<?php echo trim(Mage::getUrl('gallery/p'),'/')."#".$this->getUrlRewrite($item); if($this->_getStore()->getCode()!="default") echo '?___store='.$this->_getStore()->getCode()?>"><?php echo $item->getTitle()?></a></h5>
						<?php endif;?>
						<?php if($this->showPhotoUpdateDate($currentAlbum)):?> <label><?php echo date('M d, Y',strtotime($item->getUpdateTime()));?></label><?php endif;?>
						<?php if($this->showPhotoDescription($currentAlbum)):?>
							<p class="disp_none"><?php echo $item->getContent()?></p>
						<?php endif;?>
								<div class="star_1" style="background:transparent; padding-top: 10px; margin: 0px;">
									 <ul class="star" title="Rate This!">
									  	<li class="curr" title="<?php echo ((int)$item->getRate()) ?>" style="width: <?php echo ((int)$item->getRate()/100 * 84) ?>px;"></li>
									 </ul>
									 
								</div>
					</div>
					<?php endif;?>
				</li>
			<?php } ?>
			<?php if($this->getSlideShowPhotosAs() == Df_Gallery_Block_Gallery::$ALL_PHOTOS_OF_CATEGORY):?>
			<?php foreach($this->getPhotos() as $_photo):?>
			<h5>
				<a style="display:none;" href="<?php echo $this->helper('gallery/image')->init($_photo->getFilename())->resize($slideshowSize['width'], $slideshowSize['height'],false) ?>" rel="photo" title="<?php echo $_photo->getTitle()?>"></a>
			</h5>
			<?php endforeach;?>
			<?php endif;?>
		<?php $i++;	?>		
		</ul>
		<div class="clear_both"><span> &nbsp; </span></div>
		<div >
			<?php //echo $currentAlbum->getBottomDescription() ?>
		</div>
	</div>
	<div class="toolbar_bottom">
	<?php echo $this->getToolbar()->toHtml();?>
	</div>
	<div class="back_gallery">
		<a href="<?php echo $this->getUrl('gallery') ?>"><img src="<?php echo $this->getSkinUrl('gallery/images/back_gallery.gif') ?>" alt="<?php echo $this->__('Back to') ?>" /></a>
		<a href="<?php if($parentAlbum = $currentAlbum->getParentAlbum()) echo $parentAlbum->getUrlRewrite(); else echo Mage::getUrl();?>" class="link_backgallery"><?php if($parentAlbum = $currentAlbum->getParentAlbum()) echo $this->__('Back to')." ".$parentAlbum->getTitle(); else echo $this->__('Back to Home')?></a>
	</div>
</div>
