<?php /** @var Df_Vk_Block_Frontend_Widget $this */ ?>


<script type='text/javascript'>

	/** @type {String} */
	var scopeName = '<?php echo $this->getJavaScriptNameSpace(); ?>';

	df.namespace(['df','vk', scopeName].join('.'));

	jQuery
		.extend (
			df.vk[scopeName]
			,
			{
				enabled: true
				,
				applicationId: <?php echo $this->getApplicationId(); ?>
				,
				settings: <?php echo $this->getSettingsAsJson(); ?>
			}
		)
	;

</script>
