<?php 
$displayBlock = Mage::getStoreConfig('df_cmspro/news/show_featured_news');
if($displayBlock==1){ 
	$news=$this->getFeaturedNews();

	if($news){
	if(sizeof($news->getData())>0){
?>

<div class="mw-block-sub">
	<div class="block block-subscribe">
	    <div class="block-title">
	        <strong><span><?php echo df_helper()->cmspro()->__('Важное') ?></span></strong>
	    </div>
	<?php 
		
		$newsThumbnailSize = $this->getLatestNewsThumbnailSize();
		foreach($news as $n){?>
			<div class="block_news_item">
				<div class="block_item_img"><a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($n->getUrlRewriteId())->getRequestPath(); ?>"><img src="<?php echo $this->helper('df_cmspro/image')->init($n->getImages())->resize($newsThumbnailSize['width'], $newsThumbnailSize['height']) ?>" alt="<?php echo ('')?>"/></a></div>
				<div class="block_item_title">
					<a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($n->getUrlRewriteId())->getRequestPath(); ?>"><?php echo $n->getTitle(); ?></a>
				</div>
				<div class="cmspro_clear">&nbsp;</div>
			</div>
		<?php }
	?>
	</div>
</div>
	<?php } ?>
<?php } 
	}
?>