<?php /** @var Mage_Core_Block_Template  $this */ ?>
<?php
	/** @var Df_Qa_Model_Message_Failure $model */
	$model = $this->getData (Df_Qa_Model_Message_Failure::BLOCK_PARAM__MODEL);

	df_assert ($model instanceof Df_Qa_Model_Message_Failure);


	/** @var string $currentUrl */
    $currentUrl = df_current_url();

	/** @var string $magentoVersion */
	$magentoVersion = rm_version_full();

	/** @var string $phpVersion */
	$phpVersion = phpversion();

	/** @var string $failureMessage */
	$failureMessage = $model->getFailureMessage();

	/** @var string $traceAsText */
	$traceAsText = $model->getTraceAsText();

echo <<<TEXT

URL:                {$currentUrl}
Версия Magento:     {$magentoVersion}
Версия PHP:         {$phpVersion}

***********************************
{$failureMessage}
***********************************

{$traceAsText}
TEXT;
