<?php /** @var Mage_Core_Block_Template  $this */ ?>
<?php
	/** @var Df_Qa_Model_Message_Notification $model */
	$model = $this->getData (Df_Qa_Model_Message_Notification::BLOCK_PARAM__MODEL);

	df_assert ($model instanceof Df_Qa_Model_Message_Notification);
	/** @var string $currentUrl */
    $currentUrl = df_current_url();

	/** @var string $magentoVersion */
	$magentoVersion = rm_version_full();

	/** @var string $phpVersion */
	$phpVersion = phpversion();

	/** @var string $notificationMessage */
	$notificationMessage = $model->getNotification();

echo <<<TEXT

URL:                {$currentUrl}
Версия Magento:     {$magentoVersion}
Версия PHP:         {$phpVersion}

***********************************
{$notificationMessage}
***********************************
TEXT;
