<?php
	/**
	 * Нижеследующая стандартная для Magento разметка HTML
 	 * вместо простого echo $this->getDescription();
 	 * позволяет скрывать описание способа оплаты,
 	 * когда способ оплаты не является текущим.
	 */
?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to Chronopay website when you place an order.') ?>
        </li>
    </ul>
</fieldset>