<?php /**
	Шаблон для Magento версии < 1.1.
	Для Magento версий от 1.1 модуль использует шаблон form-ge-1.1.phtml из той же папки
*/ ?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">

    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_owner"><?php echo $this->__('Name on Card') ?><span class="required"> *</span></label> <br/>
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>

    <li>
        <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?><span class="required"> *</span></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?><span class="required"> *</span></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?><span class="required"> *</span></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>

    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?><span class="required"> *</span></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
            <a href="form.phtml#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>


		<input type="hidden" name="payment[client_local_time]" id="<?php echo $_code ?>_client_local_time"/>
		<input type="hidden" name="payment[client_screen_resolution]" id="<?php echo $_code ?>_client_screen_resolution"/>

		<script type="text/javascript">
			document.getElementById ("<?php echo $_code ?>_client_local_time").value =
				(new Date ()).toString ()
			;
			document.getElementById ("<?php echo $_code ?>_client_screen_resolution").value =
				[screen.width, screen.height, screen.colorDepth].join("x")
			;
		</script>
    </li>
</ul>



